# Generated by Django 2.0.4 on 2018-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='file1bin',
        ),
        migrations.AddField(
            model_name='case',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('C', 'Complete')], default='N', max_length=1),
        ),
    ]
