# Generated by Django 2.0.4 on 2018-05-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0002_auto_20180529_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HoldApp.Packet'),
        ),
    ]
