# Generated by Django 2.0.4 on 2018-06-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0005_packet_assigneduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'HType'), ('D', 'DType'), ('C', 'CType')], max_length=1, null=True),
        ),
    ]
