# Generated by Django 2.0.4 on 2018-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0006_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='level',
            field=models.CharField(choices=[('0', 'Match'), ('1', 'Easy'), ('2', 'Medium'), ('3', 'Difficult')], default='3', max_length=1),
        ),
    ]
