# Generated by Django 2.0.4 on 2018-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldApp', '0007_case_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_in_progress',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
